services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: paulofranklins
      POSTGRES_PASSWORD: paulofranklins
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

  paulofranklins-api:
    container_name: paulofranklins-api
    image: paulofranklins/paulofranklins-api
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/customer"
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped

  paulofranklins-react:
    container_name: paulofranklins-react
    image: paulofranklins/paulofranklins-react
    build:
      context: frontend/react-api
      args:
        api_base_url: "http://localhost:8088"
    ports:
      - "3000:5173"
    depends_on:
      - paulofranklins-api
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: