aws:
  s3:
    mock: false

spring:
  datasource:
    url: jdbc:postgresql://awseb-e-kjuczbhrsm-stack-awsebrdsdatabase-faun0uv7hgjk.ca0kr3wc8wgt.us-west-1.rds.amazonaws.com:5432/ebdb
    username: paulofranklins
    password: paulofranklins